scikit-hep/decaylanguage

.ci/azure-steps.yml, README.md, azure-pipelines.yml
This is a first draft of an azure build.
=> Adding Azure

decaylanguage/data/README.rst, tests/data/README.rst
A trivial little README for test decay files.
=> Add a README for test decay files

decaylanguage/decay/decay.py, tests/decay/test_decay.py
This is the first class for the design of a digital representation of full decay chains.
Take it as a building block. It's a convenient way to store final states and make it easy to count all species of particles across decay chains.
=> DaughtersDict class

README.md
The README is out-of-date and I tried to add a little summary and a few lines on the parsing functionality.
I also tried to follow a bit the structure in the Particle package, for consistency.
There is more to be added to the README for what concerns decay chain maipulations, but it makes sense to wait for the design to be more stable. This can go in now, for our presentations.
=> README update with summary of package goal, etc.

decaylanguage/decay/viewer.py, decaylanguage/modeling/amplitudechain.py, environment.yml, notebooks/DecayLanguageDemo.ipynb, tests/decay/test_viewer.py
Fixes as well. Direct viz in notebook.
=> Updates for demo

decaylanguage/dec/dec.py, decaylanguage/decay/viewer.py, tests/data/test_Xicc2XicPiPi.dec, tests/decay/test_viewer.py, tests/test_dec.py
Addresses https://github.com/scikit-hep/decaylanguage/issues/50.
It also addresses trouble found by @dbobulsk parsing her user files.
=> New class constructors for DecFileParser

.ci/azure-wheel.yml, azure-pipelines.yml
Azure now builds universal wheels for DecayLanguage.
=> Add wheel generation

decaylanguage/decay/decay.py
This is the third and main class for the design of a digital representation of full decay chains.
It's a convenient way to store an entire decay chain/tree, making use of the DecayMode class.
=> DecayChain class

README.md
Re-arranging the badges a bit to have a better layout.
=> Add Scikit-HEP project badge

CHANGELOG.md, environment.yml, setup.py
Update for dependency on `Particle` was a must. I "refreshed" some other dependencies, while at it.
=> Dependencies update

azure-pipelines.yml
See what the status of the issue https://github.com/scikit-hep/decaylanguage/issues/55 is.
=> WIP: Recheck Python 2.7 on Linux

.pre-commit-config.yaml, decaylanguage/__init__.py, decaylanguage/data/__init__.py, decaylanguage/dec/__init__.py, decaylanguage/dec/dec.py, decaylanguage/dec/decparser.py, decaylanguage/decay/__init__.py, decaylanguage/decay/decay.py, decaylanguage/decay/viewer.py, decaylanguage/modeling/amplitudechain.py, decaylanguage/modeling/decay.py, decaylanguage/modeling/goofit.py, decaylanguage/utils/__init__.py, decaylanguage/utils/errors.py, decaylanguage/utils/particleutils.py, decaylanguage/utils/utilities.py, docs/conf.py, setup.cfg, tests/dec/test_dec.py, tests/decay/test_decay.py, tests/decay/test_viewer.py, tests/test_dec_full.py
- chore: activate more developer guidelines
- style: pre-commit run -a for pyupgrade
- style: fix flake8 issues
- fix: correct all flake8 warnings
=> style: developer guide

.pre-commit-config.yaml, setup.cfg, src/decaylanguage/data/__init__.py, src/decaylanguage/dec/dec.py, src/decaylanguage/dec/decparser.py, src/decaylanguage/decay/decay.py, src/decaylanguage/decay/viewer.py, src/decaylanguage/modeling/__init__.py, src/decaylanguage/modeling/ampgen2goofit.py, src/decaylanguage/modeling/amplitudechain.py, src/decaylanguage/modeling/decay.py, src/decaylanguage/modeling/goofit.py, src/decaylanguage/utils/errors.py, src/decaylanguage/utils/particleutils.py, src/decaylanguage/utils/utilities.py
This just does a basic "untyped" mypy check, and still managed to find a few issues. I'll comment on a few of the changes, but in general, mostly just masked them out for now, with 1-3 real fixes.
=> fix: add mypy and fix/hide issues

src/decaylanguage/dec/dec.py, tests/dec/test_dec.py
Dear @eduardo-rodrigues,
This is a based on a discussion on `lhcb-simulation`, where we presented our opinionated `.dec` file printer.
I cleaned it up a bit, and would like to hear your opinions on upstreaming this. We modified the `print_decay_modes` so that elements are maximally aligned for a given decay.
For example, in `master`, the print function gives:
```
Decay B0sig
0.0031 : MyD'_1-  mu+  nu_mu                                           ISGW [2.0]
0.003 : MyD_0*-  mu+  nu_mu                                           ISGW [2.0]
0.0028 : MyD_1-  mu+  nu_mu                                            ISGW [2.0]
0.0012 : MyD_2*-  mu+  nu_mu                                           ISGW [2.0]
Decay Mytau-
0.1736 : mu-  nu_tau  anti-nu_mu                                   TAULNUNU …
```
=> An opinionated .dec file printer/prettifier

.pre-commit-config.yaml, pyproject.toml, setup.cfg, src/decaylanguage/dec/decparser.py
@eduardo-rodrigues I've updated the config - and this one mypy error is left:
```
src/decaylanguage/dec/decparser.py:92: error: "Type[Particle]" has no attribute "from_search_list"
```
Is this correct, is that something we changed?
=> chore: bump mypy and move to toml config

.github/workflows/ci.yml
Closes https://github.com/scikit-hep/decaylanguage/issues/156.
=> Run the CI on Linux, MacOS and Windows

.pre-commit-config.yaml, docs/conf.py, pyproject.toml, setup.cfg, src/decaylanguage/__init__.py, src/decaylanguage/__main__.py, src/decaylanguage/dec/__init__.py, src/decaylanguage/dec/dec.py, src/decaylanguage/dec/decparser.py, src/decaylanguage/decay/__init__.py, src/decaylanguage/decay/decay.py, src/decaylanguage/decay/viewer.py, src/decaylanguage/modeling/__init__.py, src/decaylanguage/modeling/ampgen2goofit.py, src/decaylanguage/modeling/amplitudechain.py, src/decaylanguage/modeling/decay.py, src/decaylanguage/modeling/goofit.py, src/decaylanguage/utils/__init__.py, src/decaylanguage/utils/errors.py, src/decaylanguage/utils/particleutils.py, src/decaylanguage/utils/utilities.py, tests/dec/test_dec.py, tests/dec/test_issues.py, tests/decay/test_decay.py, tests/decay/test_viewer.py, tests/test_convert.py, tests/test_dec_full.py
To better follow Scikit-HEP guidelines :-).
=> Add isort to pre-commit hooks

.github/workflows/ci.yml, noxfile.py, setup.cfg, src/decaylanguage/dec/dec.py, src/decaylanguage/modeling/ampgentransform.py, tests/decay/test_viewer.py
This fixes a few things, corrects the warnings showing up in the tests, and also bumps lark because it doesn't seem to break anything to do so? Maybe it was a bug that was fixed? Closes #130
=> chore: update and fix warnings

src/decaylanguage/__init__.py, src/decaylanguage/dec/__init__.py, src/decaylanguage/decay/__init__.py, src/decaylanguage/modeling/__init__.py, src/decaylanguage/utils/__init__.py
Following the recent discussion https://github.com/scikit-hep/particle/pull/326#discussion_r693195612 in the `Particle` package.
=> Add __dir__() to all __init__ files

CHANGELOG.md, environment.yml, setup.cfg, src/decaylanguage/decay/viewer.py, src/decaylanguage/modeling/decay.py
Fixes https://github.com/scikit-hep/decaylanguage/issues/211.
=> Adapt to work with graphviz >= 0.19 that broke parts of the API

CHANGELOG.md, environment.yml, setup.cfg, tests/decay/test_viewer.py
CHANGELOG:
```
Package dependent on Python 3 only ``Particle`` version 0.20.
Otherwise identical to series 0.13.
```
=> Prepare release 0.14.0

.github/workflows/ci.yml
Closes https://github.com/scikit-hep/decaylanguage/issues/218.
A check of `AmpGen2GooFit D2K3p.ipynb` is skipped, see discussion below.
=> Test notebooks in the CI

src/decaylanguage/decay/decay.py
Let me know if you see anything worth changing and/or improving to these doc updates.
=> Decay representations: more doc

README.md
=> docs: Fix link to decay files in readme

src/decaylanguage/dec/dec.py, tests/data/test_example_Dst.dec, tests/dec/test_dec.py
I still need to add examples and tests ...
This enhancement may be of interest to you, @yipengsun.
=> Enhance DecFileParser.print_decay_modes function

.github/matchers/pylint.json, .github/workflows/ci.yml, noxfile.py, pyproject.toml, src/decaylanguage/__main__.py, src/decaylanguage/data/__init__.py, src/decaylanguage/dec/dec.py, src/decaylanguage/decay/decay.py, src/decaylanguage/modeling/ampgen2goofit.py, src/decaylanguage/modeling/ampgentransform.py, src/decaylanguage/modeling/amplitudechain.py, src/decaylanguage/modeling/decay.py, src/decaylanguage/modeling/goofit.py, src/decaylanguage/utils/utilities.py
=> chore: add pylint

README.md
@all-contributors
please add @eduardo-rodrigues for maintenance, code, doc.
please add @henryiii for maintenance, code, doc.
=> docs: add package contributors

README.md, environment.yml, notebooks/ExampleDecFileParsingWithLark.ipynb, pyproject.toml, src/decaylanguage/data/WorkingOutModel.ipynb, src/decaylanguage/dec/dec.py, tests/test_dec_full.py
Closes https://github.com/scikit-hep/decaylanguage/issues/280.
=> Adapt to Python 3 only Lark 1.x

.flake8, .pre-commit-config.yaml, pyproject.toml, src/decaylanguage/dec/dec.py, src/decaylanguage/decay/decay.py, src/decaylanguage/decay/viewer.py, src/decaylanguage/modeling/ampgentransform.py, src/decaylanguage/modeling/goofit.py, tests/dec/test_dec.py, tests/dec/test_issues.py, tests/decay/test_decay.py, tests/decay/test_viewer.py, tests/test_convert.py, tests/test_dec_full.py, tests/utils/test_particleutils.py
- chore: move to using Ruff
- style: run ruff
- chore: fix remaining Ruff issues
=> chore: move to Ruff

src/decaylanguage/dec/dec.py, src/decaylanguage/decay/decay.py, src/decaylanguage/decay/viewer.py, tests/dec/test_dec.py, tests/decay/test_viewer.py
Following up from https://github.com/scikit-hep/decaylanguage/pull/308.
=> Better test coverage for dec and decay submodules

environment.yml, pyproject.toml
Seems reasonable especially that 1.7.0 contains several improvements and bug fixes wrt 1.6.9.
=> Require plumbum>=1.7.0

src/decaylanguage/data/decfile.lark, tests/data/minimalistic.dec, tests/dec/test_dec.py
This is relevant to LHCb. Cc @admorris.
=> Add support for empty or minimalistic decay files

CHANGELOG.md
FYI @admorris, I'm making a release with all recent developments resulting from your work on LHCb, plus a few little things.
=> Prepare release 0.15.4

CHANGELOG.md
Closes https://github.com/scikit-hep/decaylanguage/issues/349 - FYI @jonas-eschle.
=> Prepare release 0.15.5

CHANGELOG.md
=> Prepare for release 0.16.0

tests/data/models/model-BaryonPCR.dec, tests/data/models/model-GOITY_ROBERTS.dec, tests/data/models/model-LNUGAMMA.dec, tests/data/models/model-PHSP.dec, tests/data/models/model-SSD_CP.dec, tests/dec/test_dec.py, tests/dec/test_known_decay_models.py
Start addressing https://github.com/scikit-hep/decaylanguage/issues/357.
=> Test suite to verify all EvtGen models are parsed correctly - take 1

tests/data/models/model-BTOXSGAMMA.dec, tests/data/models/model-BTOXSLL.dec, tests/data/models/model-ETA_PI0DALITZ.dec, tests/data/models/model-OMEGA_DALITZ.dec, tests/data/models/model-TSS.dec, tests/data/models/model-YMSTOYNSPIPICLEO.dec, tests/data/models/model-YMSTOYNSPIPICLEOBOOST.dec, tests/dec/test_known_decay_models.py
Follow-up  from https://github.com/scikit-hep/decaylanguage/pull/361, continuing adding more models to the test suite.
=> Test suite to verify all EvtGen models are parsed correctly - take 2

tests/data/models/model-BTOSLLMS.dec, tests/data/models/model-D0GAMMADALITZ.dec, tests/data/models/model-DToKpienu.dec, tests/data/models/model-D_DALITZ.dec, tests/data/models/model-D_hhhh.dec, tests/data/models/model-FLATSQDALITZ.dec, tests/data/models/model-HQET2.dec, tests/data/models/model-HQET3.dec, tests/data/models/model-PARTWAVE.dec, tests/data/models/model-PHI_DALITZ.dec, tests/data/models/model-THREEBODYPHSP.dec, tests/dec/test_known_decay_models.py
Continuing further on https://github.com/scikit-hep/decaylanguage/pull/365 and similar PRs to deal with task https://github.com/scikit-hep/decaylanguage/issues/357.
=> Test suite to verify all EvtGen models are parsed correctly - take 4

tests/data/models/model-BCL.dec, tests/data/models/model-BGL.dec, tests/data/models/model-BLLNUL.dec, tests/data/models/model-BNOCBPTOKSHHH.dec, tests/data/models/model-BSTOGLLISRFSR.dec, tests/data/models/model-BSTOGLLMNT.dec, tests/data/models/model-BS_MUMUKK.dec, tests/data/models/model-BTO3PI_CP.dec, tests/data/models/model-BTODDALITZCPK.dec, tests/data/models/model-BToDiBaryonlnupQCD.dec, tests/dec/test_known_decay_models.py
Continuing further on https://github.com/scikit-hep/decaylanguage/pull/372 and similar PRs to deal with task https://github.com/scikit-hep/decaylanguage/issues/357.
=> Test suite to verify all EvtGen models are parsed correctly - take 5

.pre-commit-config.yaml, src/decaylanguage/_compat/typing.py, src/decaylanguage/dec/dec.py, src/decaylanguage/decay/decay.py
Pulling just this change out of #392 to make that one easier to review.
=> chore: use Self

.github/workflows/ci.yml, README.md, pyproject.toml, src/decaylanguage/_compat/typing.py, src/decaylanguage/decay/decay.py
=> chore: drop Python 3.7, add Python 3.12

.github/workflows/wheel.yml
=> ci: attestations

.github/workflows/ci.yml, noxfile.py, pyproject.toml
Adding 3.13. Was waiting for `pywin32` -> `plumbum` to be ready, but they are now.
=> chore: add 3.13 classifier and test

CHANGELOG.md
* Parsing of decay files (aka .dec files):
- Updated to the latest Belle II's main DECAY.DEC file.
* Miscellaneous:
- Remove invalid `-y` argument to `uv pip install` in the nox script.
* CI and tests:
- Updates and clean-up to pre-commit hooks and CI YAML files.
=> Prepare for release 0.20.0
