scikit-hep/decaylanguage

- decaylanguage/dec/__init__.py
- decaylanguage/dec/enums.py
I reckon this can be useful to have available. I put it in the `enums.py` submodule to avoid having another trivial file. But we can move this to a `defs.py` file or alike, if you prefer.
> Make available the list of known decay models

- decaylanguage/dec/dec.py
- tests/test_dec.py
The parsing now produces on the fly the correct/expected number of charge-conjugate decay trees. Also, this is now done much faster - DECAY.DEC is parsed in about 2 seconds.
This should be the last work on the parser before moving on to a design of the "backend storage" for decay chains, as per our discussions. That will be a major improvement and redesign of various parts.
> DecFileParser works nicely for master DECAY.DEC

- decaylanguage/decay/decay.py
- tests/decay/test_decay.py
This is the second class for the design of a digital representation of full decay chains.
Take it as the remaining building block. It's a convenient way to store decay modes, making use of the new DaughtersDict class. The mother particle is not part of / stored in the decay mode as that's common to various decay modes, by construction - no need to duplicate info.
I will need to add some more documentation. Otherwise that's it. In particular, the test suite seems comprehensive already.
> DecayMode class

- README.md
This should fix the fact that the logo does not show on PyPI for release 0.3.0.
> Image link in README made to display on PyPI

- azure-pipelines.yml
@henryiii, this is a temporary workaround for https://github.com/scikit-hep/decaylanguage/issues/55, as I want to make a new release and the failure in Azure is annoying.
> Temporarily remove Python 2.7 checks on Linux, because of issue in Azure

- README.md
- decaylanguage/dec/dec.py
- decaylanguage/decay/viewer.py
- notebooks/DecayLanguageDemo.ipynb
- tests/dec/test_dec.py
- tests/decay/test_viewer.py
Trivial rename - I think this makes sense because the method effectively provides a series of defined (and parsed) decay chains of a given mother particle.
> Rename DecFileParser.build_decay_chain() to DecFileParser.build_decay_chains()

- decaylanguage/decay/__init__.py
DecayChainViewer will not be available at the top level if pydot is not available. See #99.
> Only export DecayChainViewer if available

- CHANGELOG.md
- decaylanguage/_version.py
- decaylanguage/decay/__init__.py
- setup.py
Fixes https://github.com/scikit-hep/decaylanguage/issues/99.
> Make pydot required, bump version to 0.6.2

- CHANGELOG.md
- decaylanguage/_version.py
- decaylanguage/modeling/ampgentransform.py
- environment.yml
- setup.py
FYI @henryiii - so it seems that we never released a version compatible with `Particle` v0.10. At this stage, and given that v0.11.0 is best, it makes sense to simply release on the later version.
> Bump version to 0.7.0

- CHANGELOG.md
- decaylanguage/_version.py
- environment.yml
- setup.py
A simple update of the dependency on `Particle`, from 0.11 to the newly released 0.12.
> Bump version to 0.8.0

- setup.py
I noticed in conda-forge/staged-recipes#12786 that the tests/ directory is being installed to site-packages as it isn't explicitly excluded.
> Don't install "tests" directory

- azure-pipelines.yml
At the moment we have a mix of tests. Something to improve at some stage. In any case it is important to have tests for Python 3.8 and 3.9 on Windows.
> Add tests of Python 3.8 and 3.9 on Windows

- decaylanguage/data/decfile.lark
- decaylanguage/dec/dec.py
- tests/data/test_CopyDecay_RemoveDecay.dec
- tests/dec/test_dec.py
Address some of the possible statements of dec files that the present parser is not aware of, hence it cannot parse, see the discussions at https://github.com/scikit-hep/decaylanguage/issues/100.
FYI @daritter - I found on the web some example master decay files `DECAY.DEC `with which I could work to extend `DecayLanguage`'s parser.
> Make the decay file parser understand the CopyDecay statement

- CHANGELOG.md
- decaylanguage/_version.py
- environment.yml
Trivial patch release to fix things for Conda, see failure at https://github.com/conda-forge/decaylanguage-feedstock/pull/3.
> Release 0.10.1

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- azure-pipelines.yml
- pyproject.toml
- setup.cfg
- setup.py
Converting to setup.cfg. Automatic + minor touchup manually.
> chore: update to setup.cfg

- pyproject.toml
> tests: enable checking for warnings

- src/decaylanguage/utils/particleutils.py
- tests/utils/test_particleutils.py
Related to MR https://github.com/scikit-hep/particle/pull/354 in `Particle`, see discussions there.
This move is to somewhat clean-up `Particle` and have here the 2 functions that are only needed in `DecayLanguage`'s modeling submodule to deal with AmpGen. For reference, there are ongoing discussions to make this all redundant, at which point these fuctions will also become unnecessary.
CC @henryiii, @jonas-eschle.
> Move particle finding functions for AmpGen names to this package

- CHANGELOG.md
This is largely a patch release to get some inconsistency sorted in the Conda release (dependency on `Particle`).
> Prepare release 0.15.3

- src/decaylanguage/decay/decay.py
- tests/decay/test_decay.py
The DecayChain.from_dict constructor has buggy and given a dict describing a chain with a particle having multiple final states it would silently pick up the last one parsed. Now it raises an exception since non-single decay chains are not supported in the class.
While at it, docs enhanced with explanations and examples.
> DecayChain.from_dict only supports single decay chains

- src/decaylanguage/data/decfile.lark
- src/decaylanguage/dec/dec.py
- tests/data/defs-aliases-chargeconj.dec
- tests/dec/test_dec.py
Following up from PR https://github.com/scikit-hep/decaylanguage/pull/336.
> Start adding get methods and tests for recently added EvtGen keywords

- src/decaylanguage/data/decfile.lark
- src/decaylanguage/dec/dec.py
- tests/dec/test_dec.py
Hi @henryiii, I realised while working on get methods for recently introduced EvtGen  keywords that (1) some rules with more than one possible label cannot presently be disentangled (e.g. "ChangeMassMin" and "ChangeMassMax") and (2) the grammar can anyway be simplified, potentially making things slightly faster.
I will be adding more here but would welcome your opinion on these simplifications in case I am missing something - I think not and this has no cons, just pros. Advance thanks.
> Simplify the decay file parsing grammar and implement more get methods for EvtGen keywords + unit tests

- src/decaylanguage/data/decfile.lark
- tests/data/minimalistic.dec
- tests/data/test_stable-particle.dec
- tests/dec/test_dec.py
This is trivially done in EvtGen with an empty `Decay` statement, i.e., a statement containing no decay lines/modes.
> Allow dec file Decay statements to effectively be able to set a particle as stable

- src/decaylanguage/data/decfile.lark
- src/decaylanguage/dec/dec.py
- tests/data/defs-aliases-chargeconj.dec
- tests/dec/test_dec.py
Follows up from https://github.com/scikit-hep/decaylanguage/pull/351.
> Further simplify the decay file parsing grammar and implement more get methods for EvtGen keywords + unit tests

- .github/workflows/ci.yml
- .readthedocs.yml
- pyproject.toml
- src/decaylanguage/decay/decay.py
<h3>General</h3>
<ul>
<li>Detected build backend: <code>hatchling.build</code></li>
<li>Detected license(s): BSD License</li>
</ul>
<h3>PyProject</h3>
<table>
<tr><th>?</th><th>Name</th><th>Description</th></tr>
<tr style="color: red;">
<td><span role="img" aria-label="Failed">&#10060;</span></td>
<td>PP305</td>
<td>
<a href="https://learn.scientific-python.org/development/guides/pytest#PP305">Specifies xfail_strict</a>
<br/>
<p><code>xfail_strict</code> should be set (probably to <code>true</code>). You can manually
specify if a check should be strict when setting each xfail.</p>
</td>
</tr>
</table>
<h3>GitHub Actions</h3>
<table>
<tr><th>?</th><th>Name</th><th>Description</th></tr>
<tr style="color: red;">
<td><span role="img" aria-label="Failed">&#10060;</span></td>
<td>GH102</td> …
> chore: a few updates suggested by sp-repo-review

- .github/workflows/ci.yml
See https://github.com/scikit-hep/decaylanguage/pull/386.
> Update ci.yml to pin Python to 3.11 in pre-commit checks while pylcn gets fixed for 3.12

- .github/workflows/ci.yml
- .pre-commit-config.yaml
Reverts scikit-hep/decaylanguage#388 given that the issue with pylcn got fixed in the latest release.
> Update pylcn to 2.4.0 that supports Python 3.12

- pyproject.toml
> chore: modernize Ruff config

- .pre-commit-config.yaml
- src/decaylanguage/dec/dec.py
- src/decaylanguage/decay/decay.py
- tests/dec/test_dec.py
The changes from #392, but in a branch that won't get force pushed by pre-commit weekly. Rebased after #398. Closes #399.
> fix: support passing though dm, nicer typing

- CHANGELOG.md
* Parsing of decay files (aka .dec files):
- Major update of test suite to verify all EvtGen models are parsed correctly.
- Hence full support for all known Belle-II and LHCb EvtGen models.
- Lark parser grammar for decay files parsing refactored and simplified.
- Minor fixes to decay model parsing.
- Better type hints in decay file parsing classes.
- General test suite enhanced.
* Miscellaneous:
- Modernisation of Ruff configuration in `pyproject.toml`.
* CI and tests:
- Updates to pre-commit hooks and CI YAML files.
> Prepare for release 0.18.0

- src/decaylanguage/dec/dec.py
- tests/dec/test_dec.py
- tests/output/DtoKpipipi_v2.cu
This PR fixes #451. 
I also reduced the number of decimals printed to 5 or 7.
> Fixed bug in print_decay_modes where decays with equal BFs were skipped

- pyproject.toml
- src/decaylanguage/dec/dec.py
- tests/data/defs-aliases-chargeconj.dec
- tests/dec/test_dec.py
As such, there was a bug whe an EvtGen `Particle` statement would not define the optional width, which was taken from the particle or alias and hence returned in MeV.
> EvtGen uses GeV, not the standard HEP system of units, hence MeV!

- .github/workflows/ci.yml
The Codecov token was missing as a secret. Added now.
> Get Codecov to upload again

- CHANGELOG.md
* Dependencies:
- Package dependent on ``Particle`` >= 0.26.0 and `hepunits` >= 2.4.0.
* CI and tests:
- Updates to pre-commit hooks and CI YAML files.
> Prepare for release 0.20.1
